const cssPropertiesWithValues = {
  // 1. Layout & Positioning
  alignContent: ['stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around', 'space-evenly'],
  alignItems: ['stretch', 'center', 'flex-start', 'flex-end', 'baseline'],
  alignSelf: ['auto', 'stretch', 'center', 'flex-start', 'flex-end', 'baseline'],
  justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly'],
  justifyItems: ['start', 'end', 'center', 'stretch'],
  justifySelf: ['auto', 'start', 'end', 'center', 'stretch'],
  flex: ['none', '1 0 auto', '0 1 auto', 'inherit'],
  flexBasis: ['auto', '0', '100px', '10%', 'max-content', 'min-content'],
  flexDirection: ['row', 'row-reverse', 'column', 'column-reverse'],
  flexFlow: ['row nowrap', 'column wrap', 'row wrap', 'inherit'],
  flexGrow: ['0', '1', 'inherit'],
  flexWrap: ['nowrap', 'wrap', 'wrap-reverse'],
  grid: ['none', 'auto', 'inherit'],
  gridArea: ['auto', 'span 2 / span 3', '1 / 1 / 2 / 2', 'inherit'],
  gridAutoColumns: ['auto', 'min-content', 'max-content', '100px'],
  gridAutoFlow: ['row', 'column', 'dense', 'row dense', 'column dense'],
  gridAutoRows: ['auto', 'min-content', 'max-content', '100px'],
  gridColumn: ['auto', 'span 2', '1 / 3'],
  gridColumnEnd: ['auto', 'span 2', '3'],
  gridColumnGap: ['normal', '0', '10px', '1em'],
  gridColumnStart: ['auto', '1', '3'],
  gridGap: ['0', '10px', '1em', '5%'],
  gridRow: ['auto', 'span 2', '1 / 3'],
  gridRowEnd: ['auto', 'span 2', '3'],
  gridRowGap: ['normal', '0', '10px', '1em'],
  gridRowStart: ['auto', '1', '3'],
  gridTemplate: ['none', "'a b' 'c d'", 'auto / auto / auto', 'inherit'],
  gridTemplateAreas: ['none', "'header header' 'main aside' 'footer footer'", 'inherit'],
  gridTemplateColumns: ['none', 'auto', '100px 200px', 'repeat(3, 1fr)'],
  gridTemplateRows: ['none', 'auto', '100px 200px', 'repeat(3, 1fr)'],
  placeContent: ['stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around', 'space-evenly'],
  placeItems: ['auto', 'start', 'end', 'center', 'stretch'],
  placeSelf: ['auto', 'start', 'end', 'center', 'stretch'],
  position: ['static', 'relative', 'absolute', 'fixed', 'sticky'],
  top: ['auto', '0', '50%', '100%', '10px', '-10px'],
  bottom: ['auto', '0', '50%', '100%', '10px', '-10px'],
  left: ['auto', '0', '50%', '100%', '10px', '-10px'],
  right: ['auto', '0', '50%', '100%', '10px', '-10px'],
  zIndex: ['auto', '0', '1', '10', '100', '-1'],
  order: ['0', '1', '-1', 'inherit'],

  // 2. Sizing
  width: ['auto', '100%', '50%', '10px', '20em', 'min-content', 'max-content', 'fit-content'],
  minWidth: ['0', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  maxWidth: ['none', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  height: ['auto', '100%', '50%', '10px', '20em', 'min-content', 'max-content', 'fit-content'],
  minHeight: ['0', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  maxHeight: ['none', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  blockSize: ['auto', '100%', '50%', '10px', '20em', 'min-content', 'max-content', 'fit-content'],
  inlineSize: ['auto', '100%', '50%', '10px', '20em', 'min-content', 'max-content', 'fit-content'],
  maxBlockSize: ['none', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  maxInlineSize: ['none', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  minBlockSize: ['0', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],
  minInlineSize: ['0', '100px', '50%', 'auto', 'min-content', 'max-content', 'fit-content'],

  // 3. Spacing
  margin: ['auto', '0', '10px', '1em', '5%', '10vw'],
  marginTop: ['auto', '0', '10px', '1em', '5%', '10vw'],
  marginRight: ['auto', '0', '10px', '1em', '5%', '10vw'],
  marginBottom: ['auto', '0', '10px', '1em', '5%', '10vw'],
  marginLeft: ['auto', '0', '10px', '1em', '5%', '10vw'],
  marginBlock: ['auto', '0', '10px', '1em', '5%'],
  marginBlockStart: ['auto', '0', '10px', '1em', '5%'],
  marginBlockEnd: ['auto', '0', '10px', '1em', '5%'],
  marginInline: ['auto', '0', '10px', '1em', '5%'],
  marginInlineStart: ['auto', '0', '10px', '1em', '5%'],
  marginInlineEnd: ['auto', '0', '10px', '1em', '5%'],
  padding: ['0', '10px', '1em', '5%'],
  paddingTop: ['0', '10px', '1em', '5%'],
  paddingRight: ['0', '10px', '1em', '5%'],
  paddingBottom: ['0', '10px', '1em', '5%'],
  paddingLeft: ['0', '10px', '1em', '5%'],
  paddingBlock: ['0', '10px', '1em', '5%'],
  paddingBlockStart: ['0', '10px', '1em', '5%'],
  paddingBlockEnd: ['0', '10px', '1em', '5%'],
  paddingInline: ['0', '10px', '1em', '5%'],
  paddingInlineStart: ['0', '10px', '1em', '5%'],
  paddingInlineEnd: ['0', '10px', '1em', '5%'],
  columnGap: ['normal', '0', '10px', '1em'],
  rowGap: ['normal', '0', '10px', '1em'],
  gap: ['normal', '0', '10px', '1em'],

  // 4. Typography
  font: ['caption', 'icon', 'menu', 'message-box', 'small-caption', 'status-bar'],
  fontFamily: ['Arial', 'Helvetica', 'sans-serif', 'serif', 'Courier New', 'monospace', 'Georgia', 'inherit'],
  fontFeatureSettings: ['normal', "'liga' on", "'liga' off"],
  fontKerning: ['auto', 'normal', 'none'],
  fontSize: ['medium', 'xx-small', 'x-small', 'small', 'large', 'x-large', 'xx-large', 'smaller', 'larger', '1rem', '1em', '16px'],
  fontStyle: ['normal', 'italic', 'oblique'],
  fontVariant: ['normal', 'small-caps'],
  fontVariantCaps: ['normal', 'small-caps', 'all-small-caps', 'petite-caps', 'all-petite-caps', 'unicase', 'titling-caps'],
  fontWeight: ['normal', 'bold', 'bolder', 'lighter', '100', '200', '300', '400', '500', '600', '700', '800', '900'],
  letterSpacing: ['normal', '0', '1px', '2px', '0.1em'],
  lineHeight: ['normal', '1', '1.5', '2', '1em', '100%'],
  textAlign: ['left', 'right', 'center', 'justify'],
  textAlignLast: ['auto', 'left', 'right', 'center', 'justify'],
  textDecoration: ['none', 'underline', 'overline', 'line-through', 'blink'],
  textDecorationColor: ['currentcolor', 'red', 'blue', 'transparent'],
  textDecorationLine: ['none', 'underline', 'overline', 'line-through', 'blink'],
  textDecorationStyle: ['solid', 'double', 'dotted', 'dashed', 'wavy'],
  textEmphasis: ['none', 'accent', 'dot', 'circle', 'disc'],
  textEmphasisColor: ['currentcolor', 'red', 'blue', 'transparent'],
  textEmphasisPosition: ['over right', 'over left', 'under right', 'under left'],
  textEmphasisStyle: ['none', 'filled', 'open', 'dot', 'circle', 'double-circle', 'triangle', 'sesame'],
  textIndent: ['0', '1em', '2em', '10%'],
  textOrientation: ['mixed', 'upright', 'sideways'],
  textOverflow: ['clip', 'ellipsis'],
  textShadow: ['none', '1px 1px 2px black', '0 0 3px blue', '2px 2px red'],
  textTransform: ['none', 'capitalize', 'uppercase', 'lowercase', 'full-width'],
  textUnderlineOffset: ['auto', '0', '2px', '5px'],
  textUnderlinePosition: ['auto', 'under', 'left', 'right'],
  verticalAlign: ['baseline', 'sub', 'super', 'text-top', 'text-bottom', 'middle', 'top', 'bottom'],
  whiteSpace: ['normal', 'pre', 'nowrap', 'pre-wrap', 'pre-line'],
  wordBreak: ['normal', 'break-all', 'keep-all', 'break-word'],
  wordSpacing: ['normal', '0', '0.1em', '1em', '10px'],
  wordWrap: ['normal', 'break-word'],
  writingMode: ['horizontal-tb', 'vertical-rl', 'vertical-lr'],
  quotes: ['auto', "'<' '>'", "'“' '”'", "'«' '»'"],

  // 5. Colors & Backgrounds
  color: ['currentcolor', 'black', 'white', 'red', 'blue', 'green', 'inherit'],
  background: ['none', "url('image.jpg')", 'red', 'linear-gradient(45deg, red, blue)', 'inherit'],
  backgroundBlendMode: [
    'normal',
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'color-burn',
    'hard-light',
    'soft-light',
    'difference',
    'exclusion',
    'hue',
    'saturation',
    'color',
    'luminosity',
  ],
  backgroundClip: ['border-box', 'padding-box', 'content-box', 'text'],
  backgroundColor: ['transparent', 'red', 'blue', 'rgba(0,0,0,0.5)', 'inherit'],
  backgroundImage: ['none', "url('image.jpg')", 'linear-gradient(to right, red, blue)', 'inherit'],
  backgroundOrigin: ['padding-box', 'border-box', 'content-box'],
  backgroundPosition: ['0% 0%', '50% 50%', 'right bottom', 'top center', '10px 20px'],
  backgroundPositionX: ['left', 'center', 'right', '10px', 'inherit'],
  backgroundPositionY: ['top', 'center', 'bottom', '10px', 'inherit'],
  backgroundRepeat: ['repeat', 'repeat-x', 'repeat-y', 'no-repeat'],
  backgroundSize: ['auto', 'cover', 'contain', '100px 100px'],
  borderColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderTopColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderRightColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderBottomColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderLeftColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderBlockColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderInlineColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  borderImageSource: ['none', "url('image.jpg')", 'linear-gradient(to right, red, blue)'],
  borderImageRepeat: ['stretch', 'repeat', 'round', 'space'],
  borderImageOutset: ['0', '10px', '20%'],
  borderImageWidth: ['1', '10px', '20%', 'auto'],
  borderImageSlice: ['1', '10%', '20%', 'fill'],
  accentColor: ['auto', 'red', 'blue', 'green', 'inherit'],
  outlineColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent'],
  border: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderTop: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderRight: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderBottom: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderLeft: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderBlock: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderBlockEnd: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderBlockStart: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderInline: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderInlineEnd: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  borderInlineStart: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  outline: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  outlineStyle: ['none', 'solid', 'dotted', 'dashed', 'double', 'groove', 'ridge', 'inset', 'outset'],
  outlineWidth: ['thin', 'medium', 'thick', '1px', 'inherit'],
  outlineOffset: ['0', '2px', '5px', 'inherit'],
  boxShadow: ['none', '0 4px 8px rgba(0, 0, 0, 0.2)', 'inset 0 2px 4px rgba(0, 0, 0, 0.5)'],
  boxReflect: ['none', 'below 1px', 'above 2px', 'left 3px', 'right 4px'],
  mixBlendMode: [
    'normal',
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'color-burn',
    'hard-light',
    'soft-light',
    'difference',
    'exclusion',
    'hue',
    'saturation',
    'color',
    'luminosity',
  ],

  // 6. Borders & Outline
  borderTopLeftRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderTopRightRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderBottomLeftRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderBottomRightRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderStartStartRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderStartEndRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderEndStartRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderEndEndRadius: ['0', '5px', '10px', '50%', 'inherit'],
  borderStyle: ['none', 'solid', 'dotted', 'dashed', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderWidth: ['thin', 'medium', 'thick', '1px', 'inherit'],
  borderCollapse: ['collapse', 'separate', 'inherit'],
  borderSpacing: ['0', '10px', 'inherit'],
  paintOrder: ['normal', 'fill', 'stroke', 'markers', 'inherit'],

  // 7. Flexbox & Grid
  display: [
    'none',
    'block',
    'inline',
    'inline-block',
    'flex',
    'inline-flex',
    'grid',
    'inline-grid',
    'table',
    'inline-table',
    'table-row',
    'table-cell',
    'inherit',
  ],
  flex: ['none', '1 1 auto', '0 1 auto', '2 2 auto', 'auto'],
  flexBasis: ['auto', '0', '10px', '20%', 'inherit'],
  flexDirection: ['row', 'row-reverse', 'column', 'column-reverse', 'inherit'],
  flexFlow: ['row wrap', 'row nowrap', 'column wrap', 'column nowrap', 'inherit'],
  flexGrow: ['0', '1', '2', 'inherit'],
  flexWrap: ['nowrap', 'wrap', 'wrap-reverse', 'inherit'],
  alignContent: ['stretch', 'center', 'flex-start', 'flex-end', 'space-between', 'space-around', 'inherit'],
  alignItems: ['stretch', 'center', 'flex-start', 'flex-end', 'baseline', 'inherit'],
  alignSelf: ['auto', 'stretch', 'center', 'flex-start', 'flex-end', 'baseline', 'inherit'],
  justifyContent: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'inherit'],
  justifyItems: ['auto', 'normal', 'start', 'end', 'center', 'flex-start', 'flex-end', 'baseline', 'inherit'],
  justifySelf: ['auto', 'normal', 'start', 'end', 'center', 'stretch', 'baseline', 'inherit'],
  order: ['0', '-1', '1', 'inherit'],
  grid: ['none', 'auto', '100px / auto 1fr', 'inherit'],
  gridArea: ['auto', 'header', 'main', 'sidebar', 'footer', 'inherit'],
  gridAutoColumns: ['auto', 'min-content', 'max-content', 'minmax(10px, 100px)', 'inherit'],
  gridAutoFlow: ['row', 'column', 'row dense', 'column dense', 'inherit'],
  gridAutoRows: ['auto', 'min-content', 'max-content', 'minmax(10px, 100px)', 'inherit'],
  gridColumn: ['auto', 'span 1', 'span 2', '1 / 2', 'inherit'],
  gridColumnEnd: ['auto', 'span 1', 'span 2', 'inherit'],
  gridColumnGap: ['0', '10px', 'inherit'],
  gridColumnStart: ['auto', '1', '2', 'inherit'],
  gridGap: ['0', '10px', 'inherit'],
  gridRow: ['auto', 'span 1', 'span 2', 'inherit'],
  gridRowEnd: ['auto', 'span 1', 'span 2', 'inherit'],
  gridRowGap: ['0', '10px', 'inherit'],
  gridRowStart: ['auto', '1', '2', 'inherit'],
  gridTemplate: ['none', '100px / auto 1fr', 'inherit'],
  gridTemplateAreas: ['none', "'header header header' 'main main sidebar' 'footer footer footer'", 'inherit'],
  gridTemplateColumns: ['none', 'auto 1fr', '100px auto', 'inherit'],
  gridTemplateRows: ['none', 'auto', '100px', 'inherit'],

  // 8. Transforms & Animation
  animation: ['none', 'slide 2s', 'fade 3s ease-in-out', 'spin 5s linear infinite', 'inherit'],
  transform: ['none', 'rotate(45deg)', 'scale(1.5)', 'translateX(10px)', 'inherit'],
  transformOrigin: ['center', 'top left', 'bottom right', 'inherit'],
  transformStyle: ['flat', 'preserve-3d', 'inherit'],
  perspective: ['none', '500px', '1000px', 'inherit'],
  perspectiveOrigin: ['center', 'top left', 'bottom right', 'inherit'],
  rotate: ['0deg', '45deg', '90deg', '180deg', 'inherit'],
  scale: ['1', '1.5', '2', 'inherit'],
  translate: ['0', '10px', '50%', 'inherit'],

  // 9. Visibility & Overflow
  visibility: ['visible', 'hidden', 'collapse', 'inherit'],
  opacity: ['1', '0.5', '0', 'inherit'],
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'inherit'],
  overflowWrap: ['normal', 'break-word', 'inherit'],
  overflowX: ['visible', 'hidden', 'scroll', 'auto', 'inherit'],
  overflowY: ['visible', 'hidden', 'scroll', 'auto', 'inherit'],
  clip: ['auto', 'rect(0, 0, 0, 0)', 'inherit'],
  clipPath: ['none', 'circle(50%)', 'ellipse(50% 50%)', 'polygon(50% 0%, 0% 100%, 100% 100%)', 'inherit'],
  clear: ['none', 'left', 'right', 'both', 'inherit'],
  objectFit: ['fill', 'contain', 'cover', 'none', 'scale-down', 'inherit'],
  objectPosition: ['50% 50%', 'left top', 'center center', 'inherit'],

  // 10. Lists
  listStyle: ['none', 'disc', 'circle', 'square', 'decimal', 'lower-roman', 'upper-roman', 'lower-alpha', 'upper-alpha', 'inherit'],
  listStyleImage: ['none', "url('image.jpg')", 'inherit'],
  listStylePosition: ['inside', 'outside', 'inherit'],
  listStyleType: ['none', 'disc', 'circle', 'square', 'decimal', 'lower-roman', 'upper-roman', 'lower-alpha', 'upper-alpha', 'inherit'],

  // 11. Tables
  tableLayout: ['auto', 'fixed', 'inherit'],
  captionSide: ['top', 'bottom', 'inherit'],
  emptyCells: ['show', 'hide', 'inherit'],
  borderCollapse: ['collapse', 'separate', 'inherit'],
  borderSpacing: ['0', '10px', 'inherit'],

  // 12. Filters & Effects
  filter: [
    'none',
    'blur(5px)',
    'brightness(0.5)',
    'contrast(200%)',
    'grayscale(100%)',
    'hue-rotate(90deg)',
    'invert(100%)',
    'opacity(50%)',
    'saturate(200%)',
    'sepia(100%)',
    'drop-shadow(10px 10px 5px black)',
    'inherit',
  ],
  backdropFilter: [
    'none',
    'blur(5px)',
    'brightness(0.5)',
    'contrast(200%)',
    'grayscale(100%)',
    'hue-rotate(90deg)',
    'invert(100%)',
    'opacity(50%)',
    'saturate(200%)',
    'sepia(100%)',
    'drop-shadow(10px 10px 5px black)',
    'inherit',
  ],
  boxShadow: ['none', '0 4px 8px rgba(0, 0, 0, 0.2)', 'inset 0 2px 4px rgba(0, 0, 0, 0.5)', 'inherit'],
  boxReflect: ['none', 'below 1px', 'above 2px', 'left 3px', 'right 4px', 'inherit'],
  mixBlendMode: [
    'normal',
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'color-burn',
    'hard-light',
    'soft-light',
    'difference',
    'exclusion',
    'hue',
    'saturation',
    'color',
    'luminosity',
    'inherit',
  ],
  imageRendering: ['auto', 'crisp-edges', 'pixelated', 'inherit'],
  hyphens: ['none', 'manual', 'auto', 'inherit'],
  hyphenateCharacter: ['auto', '-', 'inherit'],

  // 13. Others
  columnCount: ['auto', '1', '2', '3', 'inherit'],
  columnFill: ['auto', 'balance', 'balance-all', 'inherit'],
  columnGap: ['normal', '10px', 'inherit'],
  columnRule: ['none', 'solid 1px black', 'dashed 2px blue', 'inherit'],
  columnRuleColor: ['currentcolor', 'black', 'red', 'blue', 'green', 'transparent', 'inherit'],
  columnRuleStyle: ['none', 'solid', 'dotted', 'dashed', 'double', 'groove', 'ridge', 'inset', 'outset', 'inherit'],
  columnRuleWidth: ['medium', 'thin', 'thick', '1px', 'inherit'],
  columnSpan: ['none', 'all', 'inherit'],
  columnWidth: ['auto', '100px', 'inherit'],
  columns: ['auto', '100px 3', '200px 2', 'inherit'],
  tabSize: ['8', '4', '2', 'inherit'],
  unicodeBidi: ['normal', 'embed', 'bidi-override', 'isolate', 'plaintext', 'inherit'],
};
